management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.mongodb.enabled=false

spring.mongodb.uri=${MONGODB_URL:mongodb://mongo:27017/acsp_profile}
spring.mongodb.name=acsp_profile

server.port=${PORT:8081}

# OpenTelemetry configuration
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.opentelemetry.metrics.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
